server:
  port: 8761
spring:
  application:
    name: discovery-service
  config:
    activate:
      on-profile: local, dev, prod
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enableSelfPreservation: true
    renewalPercentThreshold: 90
  instance:
    prefer-ip-address: true
logging:
  level:
    root: ERROR