server:
  port: 8888

spring:
#  profiles:
#    active: native
  application:
    name: config
  cloud:
    config:
      server:
        native:
          search-locations: file:///C://work//git-local-repo
        git: #default
          uri: https://github.com/nowgnas/adaptive-msa
          searchPaths: config
          default-label: main
        bootstrap: true
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh, refresh, metrics
encrypt:
  key-store:
    location: classpath:adaptive-msa.jks
    password: 123456
    alias: adaptive-msa